name: Minimal Android CI Workflow

on:
  push:
    branches:
      - main

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: GET ENV KEYS
        env:
          MAPS_API_KEY: $
        run: echo MAPS_API_KEY=\"MAPS_API_KEY\" > ./local.properties
      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/release/app-release.apk
          retention-days: 5